name: flutter_native_splash
description: Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
version: 1.3.3
homepage: https://github.com/jonbhanson/flutter_native_splash

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.3.0
  image: ^3.1.0
  meta: ^1.7.0
  path: ^1.8.0
  xml: ^5.3.1
  yaml: ^3.1.0
  universal_io: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.4
  test: any
