name: flutter_native_splash
description: Automatically generates native code for adding splash screens in Android and iOS. Customize with specific platform, background color and splash image.
version: 0.1.9
homepage: https://github.com/henriquearthur/flutter_native_splash
author: Henrique Arthur <eu@henriquearthur.com.br>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  yaml: ^2.1.16
  image: ^2.1.4
  color: ^2.1.1
  xml: ^3.2.5

dev_dependencies:
  pedantic: ^1.8.0+1