name: flutter_native_splash
description: Customize Flutter's default white native splash screen with
  background color and splash image. Supports dark mode, full screen, and more.
version: 2.1.3+1
homepage: https://github.com/jonbhanson/flutter_native_splash

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.3.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image: ^3.1.3
  js: ^0.6.3
  lint: ^1.8.2
  meta: ^1.7.0
  path: ^1.8.0
  universal_io: ^2.0.4
  xml: ^5.3.1
  yaml: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: net.jonhanson.flutter_native_splash
        pluginClass: FlutterNativeSplashPlugin
      ios:
        pluginClass: FlutterNativeSplashPlugin
      web:
        pluginClass: FlutterNativeSplashWeb
        fileName: flutter_native_splash_web.dart
